### ISSUE TITLE
Auto login error

### ISSUE THREAD

**Issue by dalareo** [daggerhart/openid-connect-generic#12]
If I choose autologin option I get:

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-login.php:63) in /var/www/html/wp-includes/pluggable.php on line 1174
```

**Comment by rwasef1830** [comment]
@dalareo Check if another plugin is sending whitespace or response before openid-connect-generic. Unless there is a situation in which openid-connect-generic is the one sending the response, then this bug is invalid.

**Comment by daggerhart** [comment]
This maybe due to our attempts at setting a cookie in in the middle of a page load.

setcookie: http://php.net/setcookie
>Like other headers, cookies must be sent before any output from your script (this is a protocol restriction). 

Offending code: https://github.com/daggerhart/openid-connect-generic/blob/master/includes/openid-connect-generic-login-form.php#L100

I suspect we need to detect the need for the cookie somewhere else (much earlier), and keep this method limited to displaying the login button.

**Comment by rwasef1830** [comment]
@daggerhart My pull request #20 addresses this.
