### ISSUE TITLE
Allow periods and spaces in usernames?

### ISSUE THREAD

**Issue by liber-tas** [daggerhart/openid-connect-generic#141]
Periods and spaces are fairly common in usernames, e.g. for Wordpress sites (which I'm working on integrating with KeyCloak). Any chance we can include those characters?

It's a simple change on one line (below). I can send a PR if needed...

https://github.com/daggerhart/openid-connect-generic/blob/f3829b48e28eeb7e8548749a90d489d886f0af45/includes/openid-connect-generic-client-wrapper.php#L526

**Comment by liber-tas** [comment]
Awesome work BTW, thank you so much @daggerhart

**Comment by daggerhart** [comment]
Hi @liber-tas,

A PR is always welcome, and I'm more likely to merge a PR quickly than I am to make a simple one myself just due to how easy it is. 

If you have a moment to submit one, what do you think about allowing dashes? Seems like people might also have dashes in their usernames.

I can also make this change if you'd rather not submit a PR. Your call.

**Comment by riccardoscix** [comment]
Hi everyone,
I'm facing the same issue described by @liber-tas .
I would like to include periods, dashes and other characters in the username, is the PR you were talking about available. Otherwise, what would be the necessary changes on the code line you were mentionig? I don't know php that well to go a and change the cose myself, I'd probably mess something up. So what should I change to include those characters?
Thanks a lot for your help!

**Comment by TimoKunze** [comment]
Maybe it would be best to add a filter for customization of the username. The current implementation generates lower case usernames. I would like to have the same usernames as provided by the OpenID provider. Of course I can just change the plugin's source code, but this makes updating the plugin more complicated.

**Comment by daggerhart** [comment]
Merged the PR for periods and spaces. I'm open to a refactoring/writing of the username generation in general. Closing this issue for now. If there is another specific username related request, another issue is welcome.
