### ISSUE TITLE
mismatch-identity after successful user creation

### ISSUE THREAD

**Issue by istvank** [daggerhart/openid-connect-generic#2]
Hi, thanks for taking up the work of @unagi! :+1: 

Before investigating the code closer, maybe my problem is a known issue already: After logging in, I get an "ERROR: Mismatch identity" message. The log says "New user created" and "Successful login for", but then comes the "mismatch-identity" error. I tried with sub, preferred_username or name, all give the same error. Our OIDC provider is available here: https://api.learning-layers.eu/o/oauth2/

Any help appreciated! Cheers

**Comment by amvanbaren** [comment]
Bump. Same error. @istvank, did you find a solution?

**Comment by daggerhart** [comment]
I'm not experiencing this issue, but I mainly use the "Login Button" approach.  

@istvank @amvanbaren  Not sure if this is the issue, but could you let me know if you're using SSO or the Login Button?  

Thanks

**Comment by amvanbaren** [comment]
@daggerhart I'm also using the login button. I tried to use the SSO approach to see if that makes a difference, but the issue still persists. From what I've seen the plugin does a successfull login, then does a redirect (statuscode 302) to the home page, but after that the login page is loaded again (statuscode 200) with the error. Another thing is that the cookies (wp_sec cookies) that are being set have an expiry of the current timestamp (or maybe 15 seconds in the future).

I'll try a clean wordpress installation and see if that makes a difference. I've tried and uninstalled quite a lot of plugins, so maybe that messed up my installation.

**Comment by istvank** [comment]
It turned out to be some WordPress cookie related issue. After commenting out the failing cookie check it works. Let me check which line it was...

**Comment by amvanbaren** [comment]
I've re-installed Wordpress, with only the openid-connect-generic plugin installed. The issue persists.

@istvank Yes, the cookies seem to be messing it up. Which line did you comment? 
@daggerhart I've attached some screenshots to further illustrate the issue.
![identity-mismatch-callback](https://cloud.githubusercontent.com/assets/14129099/12398520/764b6efc-be14-11e5-9a44-99ec1744b2e5.png)
Here the cookies look like expected.

![identity-mismatch-redirect](https://cloud.githubusercontent.com/assets/14129099/12398391/c8926d92-be13-11e5-8a6e-105a1cf60578.png)
This is where things get messy. As you can see the exact same cookie is set twice. 

![identity-mismatch-login](https://cloud.githubusercontent.com/assets/14129099/12398400/d04303f8-be13-11e5-882a-8e31e456caca.png)
All the cookies are cleared and we're back at the login screen.

I don't know if the plugin can solve this issue, because it looks like its outside of the plugin's scope. Maybe mention it as a known issue and refer to @istvank's fix?

**Comment by istvank** [comment]
Here, it's this if clause: https://github.com/daggerhart/openid-connect-generic/blob/master/includes/openid-connect-generic-client-wrapper.php#L97 Commenting all the four lines out fixed it for us (thanks to @pedela). Somewhere in there the cookie has a wrong id.

**Comment by daggerhart** [comment]
@amvanbaren Those cookie screen shots are very helpful.

I think the issue is with this bit of code that sets the cookie:  https://github.com/daggerhart/openid-connect-generic/blob/master/includes/openid-connect-generic-client-wrapper.php#L292  

If I had to guess, your tokens are not coming back with an 'expires_in' key, so the cookies are being set to expire immediately.  I just took a look at the oauth spec doc, and the 'expires_in' data is optional, so I shouldn't be trying to rely on it in this way.  Also, the `current_time()` function is using GMT time, which I don't think we want.

@istvank Could you both try changing that line of code to something like:

```
$oauth_expiry = 14400 + current_time( 'timestamp' );
```

If that works, I look into a more reliable way to gather the 'expires_in' data from the provider.

Thanks again!

**Comment by amvanbaren** [comment]
@daggerhart I was looking into the same line of code :smiley: Mine does have a expires_in property, but it expires in 3.6 seconds. This is probably too little time. I'll apply your fix and see if it works.

@istvank Thanks a lot! Login finally works.

**Comment by istvank** [comment]
We also got the expires_in set. We tried with the 14400 and still the same error unfortunately.

**Comment by amvanbaren** [comment]
Tried the fix, but same result as @istvank. Looks like the cookie is not set. This is the debug output I get:
[19-Jan-2016 15:03:25 UTC] is logged in: 1
[19-Jan-2016 15:03:25 UTC] openid connect user: 1
[19-Jan-2016 15:03:25 UTC] PHP Notice:  Undefined index: openid-connect-generic-identity in /var/www/html/wp-content/plugins/openid-connect-generic-3.0.2/includes/openid-connect-generic-client-wrapper.php on line 99
[19-Jan-2016 15:03:25 UTC] has cookie:

line 99 is the 'has cookie' debug statement.

**Comment by atif-shaikh** [comment]
@daggerhart Thanks for extending the original plugin :+1: .

@istvank @amvanbaren The issue/minor mistake is, due to the flag value passed in setcookie function (https://github.com/daggerhart/openid-connect-generic/blob/master/includes/openid-connect-generic-client-wrapper.php#L293).

The 6th param/flag option 'TRUE'  passed in setcookie is for secure.

As taken from PHP Manual
-----------------------------------------
secure
Indicates that the cookie should only be transmitted over a secure HTTPS connection from the client. When set to TRUE, the cookie will only be set if a secure connection exists. On the server-side, it's on the programmer to send this kind of cookie only on secure connection (e.g. with respect to $_SERVER["HTTPS"]).

To fix simply, remove the flag or set it to false.

A genuine fix would be, to check whether, secure connection exist.
---------------------------------------------------------------------------------------
$secure = FALSE;
if( isset($_SERVER['HTTPS'] ) ) {
$secure = TRUE;
}

---
Thanks

**Comment by amvanbaren** [comment]
Good job! Didn't know that. Did some quick research and found out that Wordpress has a standard function to determine whether the connection is secure (SSL) or not. Its called [is_ssl()](https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/functions.php#L3913). The function is a bit different than the solution you're proposing, but will work in most cases.

**Comment by atif-shaikh** [comment]
@amvanbaren yeah that looks good :+1:

**Comment by daggerhart** [comment]
@atif-shaikh and @amvanbaren, That was very helpful, thanks!  I've made the change to the plugin.

@istvank could you please test the newest version to see if this resolves your problem?

Thanks again

**Comment by istvank** [comment]
Thanks, we just verified that it is working indeed.
Very much appreciated! :+1:
