### ISSUE TITLE
admin-ajax returning 0

### ISSUE THREAD

**Issue by Reccetech** [daggerhart/openid-connect-generic#34]
Hi Daggerhart,

Many thanks for all your work on this. I have installed the plugin and after authentication I just get a "0" which I understand is a problem with admin-ajax action not matching a wordpress hook. 

An example of my response that fails is:
https://mywebsite/wp-admin/admin-ajax.php?action=openid-connect-authorize?code=bbdae34ac6a040e5712fe78c9a11b828d76e08b355c618b45e9c68e05453078a&state=c2d772e1ce5c7a64eadbb758db6bdee1

The console is showing a 200 response. I am running php 7.0.18 and SSL extensions are enabled.
I saw the other thread on this issue and there does not seem to be a problem with the server returning the "action=openid-connect-authorize". I have tried turning SSL verify ON/OFF. 

On another topic :)  In the settings you request the End Session Endpoint URL. The OpenID Connect service I am using does not have sessions and many of the other OpenID Connect Plugins I have seen don't request this setting. Perhaps in future versions of the plugin you can make this optional?

Many Thanks
Keith

**Comment by daggerhart** [comment]
Hi Keith,

The first issue (admin-ajax = 0) is due to the resulting URL of your response.  It has 2 `?`s in the query string which is not being parsed correctly by php.  The resulting `$_GET` of that example is this: 
```
[
  'action' => 'openid-connect-authorize?code=bbdae34ac6a040e5712fe78c9a11b828d76e08b355c618b45e9c68e05453078a',
  'state' => 'c2d772e1ce5c7a64eadbb758db6bdee1',
]
```

If there is no way for you to fix it on the IDP end, I recommend you use the "Alternate Redirect URI" setting, which will use `/openid-connect-authorize` for the endpoint instead of `/wp-admin/admin-ajax.php`. That should avoid the issue.

Regarding the End Session Endpoint, I think you're right. At a glance, I can't see anything in the Oauth2 spec that requires this, so the setting should be optional. This setting is intended to be the "logout url" that when visited will revoke the current access to the SP. Would you please file a separate issue for this item?

Thanks,
Jonathan

**Comment by Reccetech** [comment]
It was indeed a problem with the IDP server inserting an extra ?. Working now. We can close this.

Thanks,
Keith
