### ISSUE TITLE
WordPress Plugin Directory?

### ISSUE THREAD

**Issue by lliming** [daggerhart/openid-connect-generic#61]
This is more a question than an "issue," though it's an issue for me.  I'm wondering whether we can get this plugin added to the WordPress Plugin Directory (https://wordpress.org/plugins/developers/).  This would allow novice WordPress users to use this plugin without going to GitHub, cloning the repo, and uploading to their server. 

The reason this is an issue for me is that I want to recommend this plugin to the before-mentioned novices, and believe it or not, not being in the directory is an issue. Without being in the directory, it's too difficult for some to install, and others give it side-eye, wondering why it's not in the directory. The combination of non-standard installation and perceived sketchiness means that I can't currently recommend it broadly to my (potential) users.

Why do I want to recommend this plugin? Actually, what I want to recommend is for certain people to use this plugin to configure their WP sites to use my OIDC service, Globus. Globus (www.globus.org) is a non-profit research data management SaaS/PaaS system for the academic and scientific research community, and part of our service is an OIDC/OAuth-based authentication service. We currently have 50,000+ researchers at 200+ institutions using Globus to login and manage data for their work. Globus allows researchers to use their campus login services (think: Berkeley, Harvard, University of Maryland--almost all of which are SAML-based--see https://www.incommon.org/federation/basics.html) to login, and it provides an OIDC/OAuth authentication service based on that. And, because academics often have accounts at more than one institution, Globus allows them to link their OIDC/OAuth identities so they can use them interchangeably and in combination. 

I want to show these researchers how to use Globus to allow their colleagues to log in to their WordPress blogs and websites using their local campus logins, and that means they need a solid, generic OIDC plugin. I've got the instructions written and I've trained early adopters to do it using this plugin already. It works great! My personal blog (https://home.leeandkristin.net/rll/) is configured this way. The sticking point is that it's not in the "official" WordPress Plugin Directory, which means something to some people.

I'd be happy to help make this happen if it would be helpful.  On the other hand, I can imagine many reasons why you might prefer to not take that step. So...my question: Is this something you want done or are you intentionally avoiding it or just not ready yet for other reasons?

**Comment by daggerhart** [comment]
Hi @lliming, 

Great question!

The main reason I didn't originally put this in the WP repo was that I am not an OpenID nor OAuth2 expert, I just needed this functionality and wasn't happy with existing solutions. Not being confident in my ability to support the OAuth2 specs is a big deal to me because this is fundamentally a security related plugin. 

Since releasing it there have a lot of great people drop into the issue queue to help make this a better plugin. Having all those extra eyes on the code makes me feel a lot better about the plugin, but I hadn't thought about putting it in the WP repo for a long time. 

Now I'm thinking why not? I'll work on cleaning up a few issues over the next week or so and submit it to the repo. There are a few small items I'd like to take care of before submitting it for plugin review (haven't ever had to do that before so I'll need to read up on what all is expected).

Thanks for bringing this to my attention! I'll update this issue as I make progress.

**Comment by daggerhart** [comment]
Alright, the plugin has been accepted and I have svn access. I'll upload it and review a little more in the next day or so.

One thing I'm not sure about, they made me change the plugin slug to `daggerhart-openid-connect-generic` because I do not legally represent openid... ¯\\\_(ツ)_/¯  Hopefully that doesn't mean that the plugin directory will be `daggerhart-openid-connect-generic` when it's downloaded through the UI, but it might. Shouldn't be a major issue, just unexpected.

In the meantime, anyone around here have some photoshop, or "finding creative commons pictures", skills? A nice plugin logo would be sweet, but not necessary 😄

**Comment by daggerhart** [comment]
This is now in the repo. Sorry for the delay.

Note: The folder name for the plugin downloaded through the repo is different because of the plugin-slug issue mentioned above. Just be sure to not have 2 versions of this plugin on your site at once, or things will probably break.

https://wordpress.org/plugins/daggerhart-openid-connect-generic/
