### ISSUE TITLE
not sync'ed with WordPress trunk

### ISSUE THREAD

**Issue by drzraf** [daggerhart/openid-connect-generic#85]
https://plugins.trac.wordpress.org/browser/daggerhart-openid-connect-generic/#trunk
https://wpackagist.org/search?q=openid-connect-generic&type=any&search=
Is it expected to be done automatically?

Could it be an option to add a `composer.json` and offer via packagist?

**Comment by sun** [comment]
@daggerhart That sounds super awesome.

Just discovered by accident that there is some traction on GitHub.  I read your (Drupal-related) blog post from years ago and that was sufficient reason for me to base my current work on top of your plugin.  Some PRs are in the pipeline! :-)

Aside from watching GitHub instead of WP.org, is there anything else we should consider? (might be worth a Wiki page on here!)

**Comment by daggerhart** [comment]
@sun that's great to hear! PRs always welcome

@drzraf I've made the required changes and put this on packagist - https://packagist.org/packages/daggerhart/openid-connect-generic-wordpress 

I haven't pushed to the WP dot org yet. My local setup appears to be broken and I wasn't able to successfully test 3.4.0. I'll try to fix it tomorrow, test, and push to the repo.

**Comment by drzraf** [comment]
seems fixed?

**Comment by daggerhart** [comment]
Finally fixed this. There was some discrepancy in the different versions available on WP repo and packagists. I incremented another version number to 3.4.1 and created new releases everywhere.
