### ISSUE TITLE
Error: Missing state

### ISSUE THREAD

**Issue by SilvanaBanana** [daggerhart/openid-connect-generic#90]
Hello,

I have problems using the plugin in my Production Environment. (On dev the login/logout worked fine...)

I get the error "Missing state", with the following error details:

![image](https://user-images.githubusercontent.com/36152088/42229069-da4a0190-7ee5-11e8-9c9d-4a5c11b984dc.png)

For me, it seems like state has a value and the parameter is there...anyone can help me out here or hint me in the right direction?

**Comment by SilvanaBanana** [comment]
Seems like the bug is "fixed" when enabling the plugin setting "return to page where login button was on successfull login"--> seems too be a problem with redirection.

Also, disabling a caching plugin was neccessary to properly logout.

**Comment by cedrox** [comment]
I don't understand, you have to disable your cache plugin for this to work ?

**Comment by SilvanaBanana** [comment]
Yes, that's at least what my colleague who's in charge for the wordpress part found out. As soon as the caching plugin was turned off, redirection worked.

**Comment by cedrox** [comment]
Thanks for the feedback :)
Then, you have to have your leave your wordpress without cache ? That's really anoying... I work with wp-rocket. Is there a way to setup something ?

**Comment by cedrox** [comment]
I finally try to deactivate my cache plugin. 
I also try to uprise State time limit to 3600.
Still experience issue. 
![cedrox-config](https://user-images.githubusercontent.com/10764310/46067360-ecec2200-c176-11e8-8767-7bbfec3e3413.png)

**Comment by prase09** [comment]
@cedrox me too facing the same error, did you got fix? if any please share.

**Comment by cedrox** [comment]
Hello, This error come from the fact that the state have a lifecycle. I manage to get something more stable thanks to the parameter State time lime. I increase to 24 hours...
Hope this help

**Comment by prase09** [comment]
@cedrox  I have increased to 24 hours still am facing this issue. Can you please suggest any other?

**Comment by hallkj4** [comment]
Has this been figured out yet? I am having the same problem, but only when I am trying to log in after being authenticated on another site.

**Comment by sarahistiqomah** [comment]
anyone solved this?

**Comment by ryancwalsh** [comment]
This plugin looks super useful (thanks, @daggerhart ! I'm very excited to have found it 😃), but currently I'm stuck on this same problem.

I don't have any WordPress caching plugin installed, and I've set the "State time limit" option to 86400 seconds (24 hours) as suggested above.

But I still get "ERROR: Missing state."  And when I temporarily edit the plugin code to try to debug where it's failing, I see that the `check_state` function of `openid-connect-generic-client.php` never contains my state string even at the beginning of the function (before removing expired states from the array).

I'm still trying to learn how this plugin works so I can fix it. I'd appreciate any suggestions, too. :-)

P.S. Not that it's relevant, but I'm trying to integrate with [Laravel Passport](https://laravel.com/docs/5.8/passport) OAuth2 so that my WordPress site is completely private (requires authentication for all pages) and relies on my Laravel site's sessions (and authentication) instead of a list of WordPress users with credentials. I.e. https://stackoverflow.com/q/35643938/470749

**Comment by ryancwalsh** [comment]
**It turns out that "Error: Missing state" was not my real problem.** That was caused by temporary changes I'd make to the plugin while trying to debug (so I reverted those changes). 

But then I ran into other problems, which seemed to relate to the fact that I was using Laravel Homestead and wasn't using Ngrok (e.g. Laravel Share). So starting to use that (and paste the Ngrok URL into the plugin option "Token Validation Endpoint URL") helped. 

But then I ran into this problem: https://github.com/daggerhart/openid-connect-generic/issues/48#issuecomment-473107215

**Comment by kitkan87** [comment]
I had the Missing state error also. I am using FusionAuth with daggerhart/openid-connect-generic.
This is on the dev side. No other plugins on wordpress except daggerhart.

I had to disabled cache in wp-config.php `define('ENABLE_CACHE', FALSE);`

Then it gave me an Invalid token response, exactly the same as #92 which I then removed everything in OpenID Scope and just used `openid` as a tag.

Then it worked.

**Comment by erbridge** [comment]
We have had the same error occur on nearly every log in request during a preiod of high load coinciding with a COVID-19 announcement. As the load dropped off, the error rate reduced. I suspect this is due to a race condition in https://github.com/daggerhart/openid-connect-generic/blob/acbd46c7173b383a2d34c12213b139d385459cfb/includes/openid-connect-generic-client.php#L260 and its sibling functions. If this code it run on multiple instances, that will read the array from the database, loop through it for a bit, then overwrite the value. If, while it's doing that, a new state is added, it would get overwritten, causing that state to be considered invalid.

**Comment by daggerhart** [comment]
@erbridge, I've submitted a PR with an approach to fixing this (#171). Would you mind taking a look?
